export const chartColors = {
  accent: "#aa3bff",
  textMain: "#F8FAFC",
  textMuted: "#64748b",
};

export const STYLES = {
  layout: {
    width: "100%",
    maxWidth: "1800px",
    minHeight: "100vh",
    margin: "0 auto",
    padding: "0 1.5rem 2rem",
    color: "#f8fafc",
    backgroundColor: "#060913",
    fontFamily: "Inter, system-ui, sans-serif",
    boxSizing: "border-box",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "1.5rem 0",
    borderBottom: "1px solid #1e293b",
    marginBottom: "2rem",
    flexWrap: "wrap",
    gap: "1rem",
  },
  brandSection: { display: "flex", alignItems: "center", gap: "1rem" },
  logoBox: {
    background: "linear-gradient(135deg, #aa3bff, #6366f1)",
    padding: "10px",
    borderRadius: "12px",
    display: "flex",
    alignItems: "center",
    flexShrink: 0,
    boxShadow: "0 4px 15px rgba(170, 59, 255, 0.12)",
  },
  brandTitle: {
    fontSize: "clamp(1.1rem, 4vw, 1.5rem)",
    fontWeight: "900",
    letterSpacing: "-1px",
    margin: 0,
  },
  brandSubtitle: { color: "#aa3bff", fontWeight: "300" },
  statusIndicator: {
    fontSize: "0.75rem",
    color: "#64748b",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginTop: "4px",
    fontWeight: "500",
  },
  statusDot: {
    width: "8px",
    height: "8px",
    background: "#00ffaa",
    borderRadius: "50%",
    boxShadow: "0 0 10px #00ffaa",
    flexShrink: 0,
  },
  headerButtons: {
    display: "flex",
    gap: "12px",
    flexWrap: "wrap",
  },
  btnSecondary: {
    background: "#0b1120",
    border: "1px solid #1e293b",
    color: "#f8fafc",
    padding: "10px 20px",
    borderRadius: "8px",
    fontSize: "0.875rem",
    fontWeight: "600",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    transition: "all 0.2s",
    whiteSpace: "nowrap",
  },
  kpiGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 260px), 1fr))",
    gap: "1.5rem",
    marginBottom: "2rem",
  },
  card: {
    background: "#0b1120",
    border: "1px solid #1e293b",
    borderRadius: "16px",
    padding: "1.5rem",
    transition: "transform 0.2s",
  },
  kpiLabel: {
    fontSize: "0.7rem",
    color: "#64748b",
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: "1px",
    margin: 0,
  },
  kpiValueBox: {
    display: "flex",
    alignItems: "baseline",
    gap: "8px",
    marginTop: "8px",
    flexWrap: "wrap",
  },
  kpiValue: (color) => ({
    fontFamily: "JetBrains Mono, monospace",
    fontSize: "clamp(1.5rem, 5vw, 2.25rem)",
    fontWeight: "700",
    margin: 0,
    color: color || "#f8fafc",
  }),
  kpiUnit: { fontSize: "0.8rem", color: "#64748b", fontWeight: "600" },
  pairStatsRow: {
    display: "flex",
    gap: "12px",
    overflowX: "auto",
    paddingBottom: "12px",
    marginBottom: "2rem",
    scrollbarWidth: "thin",
    scrollbarColor: "#1e293b transparent",
  },
  pairStatCard: {
    minWidth: "170px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 16px",
    background: "#0b1120",
    border: "1px solid #1e293b",
    borderRadius: "12px",
    flexShrink: 0,
    gap: "12px",
  },
  pairStatName: {
    fontWeight: "700",
    fontFamily: "JetBrains Mono, monospace",
    fontSize: "0.85rem",
    color: "#f8fafc",
  },
  pairStatDivider: {
    width: "1px",
    height: "20px",
    backgroundColor: "#1e293b",
    flexShrink: 0,
  },
  pairStatDetails: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
  },
  pairStatWr: (isHigh) => ({
    fontFamily: "JetBrains Mono, monospace",
    fontWeight: "700",
    fontSize: "0.875rem",
    display: "flex",
    alignItems: "center",
    gap: "6px",
    color: isHigh ? "#00ffaa" : "#ff3b69",
  }),
  dot: (active) => ({
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    background: active ? "#00ffaa" : "#64748b",
    boxShadow: active ? "0 0 6px #00ffaa" : "none",
    flexShrink: 0,
  }),
  pairStatCount: {
    fontSize: "0.65rem",
    color: "#64748b",
    textTransform: "uppercase",
    fontWeight: "600",
    marginTop: "2px",
  },
  chartHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "1.5rem",
    flexWrap: "wrap",
    gap: "8px",
  },
  chartTitle: { fontSize: "1rem", fontWeight: "800", margin: 0 },
  chartBadge: {
    fontSize: "0.65rem",
    background: "rgba(170, 59, 255, 0.12)",
    color: "#aa3bff",
    padding: "4px 10px",
    borderRadius: "20px",
    fontWeight: "800",
    textTransform: "uppercase",
    whiteSpace: "nowrap",
  },
  tableSectionTitle: {
    fontSize: "1rem",
    fontWeight: "800",
    marginBottom: "20px",
    marginTop: 0,
  },
  tableResponsive: {
    overflowX: "auto",
    width: "100%",
    WebkitOverflowScrolling: "touch",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    textAlign: "left",
    minWidth: "600px",
  },
  th: (align = "left", color) => ({
    padding: "12px",
    fontSize: "0.75rem",
    color: color || "#64748b",
    textTransform: "uppercase",
    fontWeight: "700",
    borderBottom: "1px solid #1e293b",
    textAlign: align,
    whiteSpace: "nowrap",
  }),
  td: (align = "left", weight = "400", color = "#f8fafc", mono = false) => ({
    padding: "16px 12px",
    fontSize: "0.85rem",
    borderBottom: "1px solid rgba(255,255,255,0.02)",
    textAlign: align,
    fontWeight: weight,
    color: color,
    fontFamily: mono ? "JetBrains Mono, monospace" : "inherit",
    whiteSpace: "nowrap",
  }),
  badge: (type) => ({
    padding: "4px 8px",
    borderRadius: "4px",
    fontSize: "0.7rem",
    fontWeight: "800",
    display: "inline-block",
    background:
      type === "LONG" ? "rgba(0, 255, 170, 0.1)" : "rgba(255, 59, 105, 0.1)",
    color: type === "LONG" ? "#00ffaa" : "#ff3b69",
  }),
  specialBadge: (color) => ({
    fontSize: "10px",
    background: color,
    color: "#000",
    padding: "2px 4px",
    borderRadius: "3px",
    marginLeft: "5px",
    fontWeight: "900",
  }),
  filterRow: {
    display: "flex",
    gap: "12px",
    flexWrap: "wrap",
  },
  select: {
    background: "#121b2e",
    color: "#f8fafc",
    border: "1px solid #1e293b",
    borderRadius: "8px",
    padding: "0 10px",
    fontSize: "0.85rem",
    outline: "none",
    height: "36px",
    cursor: "pointer",
  },
  loading: {
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#060913",
    color: "#f8fafc",
    padding: "1rem",
  },
};
